#ifndef GLOBAL_H
#define GLOBAL_H

 // This is a configuration file generated by CMake.
class Worldbase;
struct GlobalVar
{

static unsigned int SCR_WIDTH;
static unsigned int SCR_HEIGHT;
static unsigned int INVALID_TEX;

static Worldbase* GAME_WORLD;
};

// FILESYSTEM_H
#endif
